### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-custom-selectors#13]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by yisibl** [comment]
Done https://github.com/postcss/postcss-custom-selectors/commit/e020e3220644d1975b4dc7102d1acb1e0bec38a0

@ai @MoOx Please help me check it.

**Comment by MoOx** [comment]
Looks good. If all tests passes that's great !
