### ISSUE TITLE
When customSelectors is empty, console gets polluted

### ISSUE THREAD

**Issue by michaelchance** [postcss/postcss-custom-selectors#22]
Using cssnext, which uses this as a dependency.  I noticed that in some cases, cssnext doesn't actually use this module, but the log gets polluted with false positives, such as: 

"Warning: The selector '.ui-widget-overlay' is undefined in CSS!"

In addition to the check for `if(flag === 0)` maybe it should check if customSelectors is empty?

**Comment by MoOx** [comment]
I will push a fix asap.

**Comment by MoOx** [comment]
I pushed a PR https://github.com/postcss/postcss-custom-selectors/pull/23

I am not merging it since I am not the maintainer and don't have the right to publish (yet? poke @yisibl).
