### ISSUE TITLE
Incompatible with :matches()

### ISSUE THREAD

**Issue by MichielBijl** [postcss/postcss-custom-selectors#29]
Input:
```
@custom-selector :--button button, [role="button"];
:matches(:--button):focus {
  outline-color: royalblue;
}
```
Expected output:
```
:matches(button, [role="button"]):focus {
  outline-color: royalblue;
}
```
Actual output:
```
button:focus,
[role="button"]:focus {
  outline-color: royalblue;
}
```
Is this on purpose? If so, that seems unnecessary as [`:matches` has very good support](http://caniuse.com/#feat=matchesselector).

**Comment by MoOx** [comment]
This plugin rely on the postcss-selector-matches one. It's that simple.
